/**
 * js/sms-codegen.js — Bitsy SMS CVBasic code generator
 *
 * Key CVBasic SMS rules confirmed from official examples:
 *
 *  VPOKE: must use pre-computed #variable as address.
 *         VPOKE #c, value  ✓  (viboritas_sms.bas)
 *         VPOKE $3800+expr, value  ✗  (expression not evaluated)
 *
 *  SCREEN: does NOT work inside a PROCEDURE (only at top level / main loop)
 *
 *  BITMAP: 8 chars for DEFINE CHAR tiles, 16 chars for DEFINE SPRITE
 *
 *  Init:   CLS → MODE 4 → DEFINE → PALETTE
 *
 *  Name table: $3800, 32 cols × 28 rows, 2 bytes/cell (tile_lo, attr_hi)
 *  Room starts at col 8, row 6 → addr $3800+(6*32+8)*2 = $3990
 *  Each row: 32 cols × 2 bytes = 64 bytes. After writing 16 cells (32 bytes),
 *  skip 32 bytes to reach next row: #c = #c + 32
 */

function rgbToSms(r, g, b) {
  return (Math.min(3,Math.round(r/85)) & 3) |
         ((Math.min(3,Math.round(g/85)) & 3) << 2) |
         ((Math.min(3,Math.round(b/85)) & 3) << 4);
}

function rowToCharBitmapStr(rowStr) {   // 8-char for DEFINE CHAR
  var out = "";
  for (var x = 0; x < 8; x++) out += (rowStr && rowStr[x] === "1") ? "1" : ".";
  return out;
}

function rowToSpriteBitmapStr(rowStr) { // 16-char for DEFINE SPRITE
  var out = "";
  for (var x = 0; x < 8; x++) out += (rowStr && rowStr[x] === "1") ? "1" : ".";
  return out + "........";
}

function sanitizeDialog(txt) {
  return (txt || "...").replace(/[^A-Za-z0-9 .,!?'":;()\-]/g,"?").substring(0,30);
}

function generateBasCode(world) {
  var pal      = world.palette["0"] || [[0,0,0],[200,200,200],[255,255,255]];
  var colBg    = rgbToSms(pal[0][0],pal[0][1],pal[0][2]);
  var colTile  = rgbToSms(pal[1][0],pal[1][1],pal[1][2]);
  var colSpr   = rgbToSms(pal[2][0],pal[2][1],pal[2][2]);

  var tileIds  = Object.keys(world.tile).sort();
  var tileCharMap = {};
  tileIds.forEach(function(id,i){ tileCharMap[id] = i+1; });

  var npcIds   = Object.keys(world.sprite).filter(function(id){return id!=="A";}).sort();
  var numNpcs  = npcIds.length;
  var roomIds  = Object.keys(world.set).sort();

  var ps = world.sprite["A"];
  var pRoom = (ps && ps.set) ? ps.set : "0";
  var pX = ps ? (ps.x||4) : 4;
  var pY = ps ? (ps.y||4) : 4;
  var pRoomIdx = roomIds.indexOf(pRoom); if(pRoomIdx<0) pRoomIdx=0;

  // Name table geometry
  // Room centred at col 8, row 6 → VRAM start = $3800 + (6*32+8)*2 = $3990
  var NT_OX = 8, NT_OY = 6;
  var NT_START = (0x3800 + (NT_OY*32 + NT_OX)*2).toString(16).toUpperCase(); // "3990"

  var bas = []; function L(s){ bas.push(s===undefined?"":s); }

  L("\t' "+(world.title||"Bitsy SMS Game"));
  L("\t' Generated by Bitsy SMS");
  L();

  // Variables — one shared room_data array + wall_flag
  L("\tDIM room_data(256)");
  L("\tDIM wall_flag(256)");
  if(numNpcs>0){
    L("\tDIM npc_x("+numNpcs+")");
    L("\tDIM npc_y("+numNpcs+")");
    L("\tDIM npc_room("+numNpcs+")");
    L("\tDIM npc_dlg("+numNpcs+")");
  }
  L();

  // Init — order: CLS, MODE 4, DEFINE, PALETTE
  L("\tCLS");
  L("\tMODE 4");
  L();
  L("\tDEFINE CHAR 1,"+(tileIds.length||1)+",tile_bitmaps");
  L("\tDEFINE SPRITE 0,1,player_bitmap");
  if(numNpcs>0) L("\tDEFINE SPRITE 1,"+numNpcs+",npc_bitmaps");
  L();
  L("\tPALETTE 0,"+colBg);
  L("\tPALETTE 1,"+colTile);
  L("\tPALETTE 2,"+colTile);
  L("\tPALETTE 16,"+colSpr);
  L("\tPALETTE 17,"+colBg);
  L();

  // Game state
  L("\tpx = "+pX);
  L("\tpy = "+pY);
  L("\tcur_room = "+pRoomIdx);
  L("\tdialog_active = 0");
  L("\tdialog_idx = 0");
  L();

  if(numNpcs>0){
    npcIds.forEach(function(nid,i){
      var s=world.sprite[nid];
      var nr=roomIds.indexOf(s.set||"0"); if(nr<0)nr=0;
      L("\tnpc_x("+i+") = "+(s.x||0));
      L("\tnpc_y("+i+") = "+(s.y||0));
      L("\tnpc_room("+i+") = "+nr);
      L("\tnpc_dlg("+i+") = "+(i+1));
    });
    L();
  }

  // Initial draw
  L("\tGOSUB load_room");
  L("\tGOSUB draw_room");
  L();

  /* ── MAIN LOOP ─────────────────────────────────────── */
  L("main_loop:");
  L("\tWAIT");
  L();
  L("\tIF dialog_active THEN");
  L("\t\tIF cont1.button THEN");
  L("\t\t\tdialog_active = 0");
  L("\t\t\tGOSUB draw_room");
  L("\t\tEND IF");
  L("\t\tGOTO main_loop");
  L("\tEND IF");
  L();
  L("\tnx = px");
  L("\tny = py");
  L("\tIF cont1.left THEN nx = px - 1");
  L("\tIF cont1.right THEN nx = px + 1");
  L("\tIF cont1.up THEN ny = py - 1");
  L("\tIF cont1.down THEN ny = py + 1");
  L("\tIF nx = px AND ny = py THEN GOTO main_loop");
  L();
  L("\tIF nx < 0 OR nx > 15 THEN GOTO main_loop");
  L("\tIF ny < 0 OR ny > 15 THEN GOTO main_loop");
  L();
  L("\tIF wall_flag(nx + ny * 16) THEN GOTO main_loop");
  L();
  if(numNpcs>0){
    L("\tFOR nc = 0 TO "+(numNpcs-1));
    L("\t\tIF npc_room(nc) = cur_room AND npc_x(nc) = nx AND npc_y(nc) = ny THEN");
    L("\t\t\tdialog_idx = npc_dlg(nc)");
    L("\t\t\tdialog_active = 1");
    L("\t\t\tGOSUB show_dialog");
    L("\t\t\tGOTO main_loop");
    L("\t\tEND IF");
    L("\tNEXT nc");
    L();
  }
  L("\tGOSUB check_exits");
  L("\tIF exit_taken THEN GOTO main_loop");
  L();
  L("\tpx = nx");
  L("\tpy = ny");
  L("\tGOSUB draw_player_sprite");
  L();
  L("\tGOTO main_loop");
  L();

  /* ── SUBROUTINES ───────────────────────────────────── */
  L("check_exits:\tPROCEDURE");
  L("\texit_taken = 0");
  var hasExit=false;
  roomIds.forEach(function(rid,ridx){
    (world.set[rid].exits||[]).forEach(function(ext){
      hasExit=true;
      var di=roomIds.indexOf(ext.dest.set); if(di<0)di=0;
      L("\tIF cur_room = "+ridx+" AND nx = "+ext.x+" AND ny = "+ext.y+" THEN");
      L("\t\tcur_room = "+di);
      L("\t\tpx = "+ext.dest.x);
      L("\t\tpy = "+ext.dest.y);
      L("\t\tGOSUB load_room");
      L("\t\tGOSUB draw_room");
      L("\t\texit_taken = 1");
      L("\tEND IF");
    });
  });
  if(!hasExit) L("\t' no exits");
  L("\tEND");
  L();

  // load_room: reads room_data array and sets wall_flag from DATA tables
  L("load_room:\tPROCEDURE");
  L("\tFOR wi = 0 TO 255");
  L("\t\troom_data(wi) = 0");
  L("\t\twall_flag(wi) = 0");
  L("\tNEXT wi");
  roomIds.forEach(function(rid,ridx){
    L("\tIF cur_room = "+ridx+" THEN GOSUB load_room_"+ridx);
  });
  L("\tEND");
  L();

  // draw_room: uses pre-computed #c address (viboritas_sms.bas pattern)
  // #c starts at $3990 (VRAM addr of cell row6,col8)
  // Inner loop: VPOKE #c, tile then #c=#c+2
  // After 16 cells: #c=#c+32 to skip to next name-table row
  L("draw_room:\tPROCEDURE");
  L("\tCLS");
  // Unrolled VPOKEs with literal addresses (no expressions) - safest CVBasic approach
  L("\tGOSUB load_room_tiles");
  L("\tGOSUB draw_player_sprite");
  if(numNpcs>0){
    npcIds.forEach(function(nid,i){
      L("\tIF npc_room("+i+") = cur_room THEN");
      L("\t\t#sx = "+(NT_OX*8)+" + npc_x("+i+") * 8");
      L("\t\t#sy = "+(NT_OY*8)+" + npc_y("+i+") * 8");
      L("\t\tSPRITE "+(i+1)+",#sy,#sx,2");
      L("\tELSE");
      L("\t\tSPRITE "+(i+1)+",208,0,0");
      L("\tEND IF");
    });
  }
  L("\tEND");
  L();

  L("draw_player_sprite:\tPROCEDURE");
  L("\t#sx = "+(NT_OX*8)+" + px * 8");
  L("\t#sy = "+(NT_OY*8)+" + py * 8");
  L("\tSPRITE 0,#sy,#sx,0");
  L("\tEND");
  L();

  L("show_dialog:\tPROCEDURE");
  L("\tPRINT AT 704,\"                              \"");
  if(numNpcs>0){
    npcIds.forEach(function(nid,i){
      var t=sanitizeDialog(world.dialog[nid]||"...");
      L("\tIF dialog_idx = "+(i+1)+" THEN PRINT AT 704,\""+t+"\"");
    });
  }
  L("\tEND");
  L();

  /* ── PER-ROOM LOAD PROCEDURES ──────────────────────── */
  roomIds.forEach(function(rid,ridx){
    var s=world.set[rid];
    var wallIds=s.walls||[];
    L("load_room_"+ridx+":\tPROCEDURE");
    L("\tRESTORE room_"+ridx+"_data");
    L("\tFOR rd = 0 TO 255");
    L("\t\tREAD BYTE room_data(rd)");
    L("\tNEXT rd");
    // Mark wall positions
    for(var y=0;y<16;y++){
      var row=s.tilemap[y]||"0000000000000000";
      for(var x=0;x<16;x++){
        var ch=row[x]||"0";
        if(ch!=="0" && wallIds.indexOf(ch)>=0)
          L("\twall_flag("+(x+y*16)+") = 1");
      }
    }
    L("\tEND");
    L();

    // Room data: 256 tile-index bytes, 8 per DATA BYTE line
    L("room_"+ridx+"_data:");
    var tiles=[];
    for(var y=0;y<16;y++){
      var row=s.tilemap[y]||"0000000000000000";
      for(var x=0;x<16;x++){
        var ch=row[x]||"0";
        tiles.push(ch==="0"?0:(tileCharMap[ch]||0));
      }
    }
    for(var di=0;di<tiles.length;di+=8)
      L("\tDATA BYTE "+tiles.slice(di,di+8).join(","));
    L();
  });

  /* ── BITMAP DATA ───────────────────────────────────── */
  // Unrolled VPOKE procedure - 256 literal address writes
  L("load_room_tiles:\tPROCEDURE");
  L("\t\tVPOKE $3990,room_data(0)");
  L("\t\tVPOKE $3992,room_data(1)");
  L("\t\tVPOKE $3994,room_data(2)");
  L("\t\tVPOKE $3996,room_data(3)");
  L("\t\tVPOKE $3998,room_data(4)");
  L("\t\tVPOKE $399A,room_data(5)");
  L("\t\tVPOKE $399C,room_data(6)");
  L("\t\tVPOKE $399E,room_data(7)");
  L("\t\tVPOKE $39A0,room_data(8)");
  L("\t\tVPOKE $39A2,room_data(9)");
  L("\t\tVPOKE $39A4,room_data(10)");
  L("\t\tVPOKE $39A6,room_data(11)");
  L("\t\tVPOKE $39A8,room_data(12)");
  L("\t\tVPOKE $39AA,room_data(13)");
  L("\t\tVPOKE $39AC,room_data(14)");
  L("\t\tVPOKE $39AE,room_data(15)");
  L("\t\tVPOKE $39D0,room_data(16)");
  L("\t\tVPOKE $39D2,room_data(17)");
  L("\t\tVPOKE $39D4,room_data(18)");
  L("\t\tVPOKE $39D6,room_data(19)");
  L("\t\tVPOKE $39D8,room_data(20)");
  L("\t\tVPOKE $39DA,room_data(21)");
  L("\t\tVPOKE $39DC,room_data(22)");
  L("\t\tVPOKE $39DE,room_data(23)");
  L("\t\tVPOKE $39E0,room_data(24)");
  L("\t\tVPOKE $39E2,room_data(25)");
  L("\t\tVPOKE $39E4,room_data(26)");
  L("\t\tVPOKE $39E6,room_data(27)");
  L("\t\tVPOKE $39E8,room_data(28)");
  L("\t\tVPOKE $39EA,room_data(29)");
  L("\t\tVPOKE $39EC,room_data(30)");
  L("\t\tVPOKE $39EE,room_data(31)");
  L("\t\tVPOKE $3A10,room_data(32)");
  L("\t\tVPOKE $3A12,room_data(33)");
  L("\t\tVPOKE $3A14,room_data(34)");
  L("\t\tVPOKE $3A16,room_data(35)");
  L("\t\tVPOKE $3A18,room_data(36)");
  L("\t\tVPOKE $3A1A,room_data(37)");
  L("\t\tVPOKE $3A1C,room_data(38)");
  L("\t\tVPOKE $3A1E,room_data(39)");
  L("\t\tVPOKE $3A20,room_data(40)");
  L("\t\tVPOKE $3A22,room_data(41)");
  L("\t\tVPOKE $3A24,room_data(42)");
  L("\t\tVPOKE $3A26,room_data(43)");
  L("\t\tVPOKE $3A28,room_data(44)");
  L("\t\tVPOKE $3A2A,room_data(45)");
  L("\t\tVPOKE $3A2C,room_data(46)");
  L("\t\tVPOKE $3A2E,room_data(47)");
  L("\t\tVPOKE $3A50,room_data(48)");
  L("\t\tVPOKE $3A52,room_data(49)");
  L("\t\tVPOKE $3A54,room_data(50)");
  L("\t\tVPOKE $3A56,room_data(51)");
  L("\t\tVPOKE $3A58,room_data(52)");
  L("\t\tVPOKE $3A5A,room_data(53)");
  L("\t\tVPOKE $3A5C,room_data(54)");
  L("\t\tVPOKE $3A5E,room_data(55)");
  L("\t\tVPOKE $3A60,room_data(56)");
  L("\t\tVPOKE $3A62,room_data(57)");
  L("\t\tVPOKE $3A64,room_data(58)");
  L("\t\tVPOKE $3A66,room_data(59)");
  L("\t\tVPOKE $3A68,room_data(60)");
  L("\t\tVPOKE $3A6A,room_data(61)");
  L("\t\tVPOKE $3A6C,room_data(62)");
  L("\t\tVPOKE $3A6E,room_data(63)");
  L("\t\tVPOKE $3A90,room_data(64)");
  L("\t\tVPOKE $3A92,room_data(65)");
  L("\t\tVPOKE $3A94,room_data(66)");
  L("\t\tVPOKE $3A96,room_data(67)");
  L("\t\tVPOKE $3A98,room_data(68)");
  L("\t\tVPOKE $3A9A,room_data(69)");
  L("\t\tVPOKE $3A9C,room_data(70)");
  L("\t\tVPOKE $3A9E,room_data(71)");
  L("\t\tVPOKE $3AA0,room_data(72)");
  L("\t\tVPOKE $3AA2,room_data(73)");
  L("\t\tVPOKE $3AA4,room_data(74)");
  L("\t\tVPOKE $3AA6,room_data(75)");
  L("\t\tVPOKE $3AA8,room_data(76)");
  L("\t\tVPOKE $3AAA,room_data(77)");
  L("\t\tVPOKE $3AAC,room_data(78)");
  L("\t\tVPOKE $3AAE,room_data(79)");
  L("\t\tVPOKE $3AD0,room_data(80)");
  L("\t\tVPOKE $3AD2,room_data(81)");
  L("\t\tVPOKE $3AD4,room_data(82)");
  L("\t\tVPOKE $3AD6,room_data(83)");
  L("\t\tVPOKE $3AD8,room_data(84)");
  L("\t\tVPOKE $3ADA,room_data(85)");
  L("\t\tVPOKE $3ADC,room_data(86)");
  L("\t\tVPOKE $3ADE,room_data(87)");
  L("\t\tVPOKE $3AE0,room_data(88)");
  L("\t\tVPOKE $3AE2,room_data(89)");
  L("\t\tVPOKE $3AE4,room_data(90)");
  L("\t\tVPOKE $3AE6,room_data(91)");
  L("\t\tVPOKE $3AE8,room_data(92)");
  L("\t\tVPOKE $3AEA,room_data(93)");
  L("\t\tVPOKE $3AEC,room_data(94)");
  L("\t\tVPOKE $3AEE,room_data(95)");
  L("\t\tVPOKE $3B10,room_data(96)");
  L("\t\tVPOKE $3B12,room_data(97)");
  L("\t\tVPOKE $3B14,room_data(98)");
  L("\t\tVPOKE $3B16,room_data(99)");
  L("\t\tVPOKE $3B18,room_data(100)");
  L("\t\tVPOKE $3B1A,room_data(101)");
  L("\t\tVPOKE $3B1C,room_data(102)");
  L("\t\tVPOKE $3B1E,room_data(103)");
  L("\t\tVPOKE $3B20,room_data(104)");
  L("\t\tVPOKE $3B22,room_data(105)");
  L("\t\tVPOKE $3B24,room_data(106)");
  L("\t\tVPOKE $3B26,room_data(107)");
  L("\t\tVPOKE $3B28,room_data(108)");
  L("\t\tVPOKE $3B2A,room_data(109)");
  L("\t\tVPOKE $3B2C,room_data(110)");
  L("\t\tVPOKE $3B2E,room_data(111)");
  L("\t\tVPOKE $3B50,room_data(112)");
  L("\t\tVPOKE $3B52,room_data(113)");
  L("\t\tVPOKE $3B54,room_data(114)");
  L("\t\tVPOKE $3B56,room_data(115)");
  L("\t\tVPOKE $3B58,room_data(116)");
  L("\t\tVPOKE $3B5A,room_data(117)");
  L("\t\tVPOKE $3B5C,room_data(118)");
  L("\t\tVPOKE $3B5E,room_data(119)");
  L("\t\tVPOKE $3B60,room_data(120)");
  L("\t\tVPOKE $3B62,room_data(121)");
  L("\t\tVPOKE $3B64,room_data(122)");
  L("\t\tVPOKE $3B66,room_data(123)");
  L("\t\tVPOKE $3B68,room_data(124)");
  L("\t\tVPOKE $3B6A,room_data(125)");
  L("\t\tVPOKE $3B6C,room_data(126)");
  L("\t\tVPOKE $3B6E,room_data(127)");
  L("\t\tVPOKE $3B90,room_data(128)");
  L("\t\tVPOKE $3B92,room_data(129)");
  L("\t\tVPOKE $3B94,room_data(130)");
  L("\t\tVPOKE $3B96,room_data(131)");
  L("\t\tVPOKE $3B98,room_data(132)");
  L("\t\tVPOKE $3B9A,room_data(133)");
  L("\t\tVPOKE $3B9C,room_data(134)");
  L("\t\tVPOKE $3B9E,room_data(135)");
  L("\t\tVPOKE $3BA0,room_data(136)");
  L("\t\tVPOKE $3BA2,room_data(137)");
  L("\t\tVPOKE $3BA4,room_data(138)");
  L("\t\tVPOKE $3BA6,room_data(139)");
  L("\t\tVPOKE $3BA8,room_data(140)");
  L("\t\tVPOKE $3BAA,room_data(141)");
  L("\t\tVPOKE $3BAC,room_data(142)");
  L("\t\tVPOKE $3BAE,room_data(143)");
  L("\t\tVPOKE $3BD0,room_data(144)");
  L("\t\tVPOKE $3BD2,room_data(145)");
  L("\t\tVPOKE $3BD4,room_data(146)");
  L("\t\tVPOKE $3BD6,room_data(147)");
  L("\t\tVPOKE $3BD8,room_data(148)");
  L("\t\tVPOKE $3BDA,room_data(149)");
  L("\t\tVPOKE $3BDC,room_data(150)");
  L("\t\tVPOKE $3BDE,room_data(151)");
  L("\t\tVPOKE $3BE0,room_data(152)");
  L("\t\tVPOKE $3BE2,room_data(153)");
  L("\t\tVPOKE $3BE4,room_data(154)");
  L("\t\tVPOKE $3BE6,room_data(155)");
  L("\t\tVPOKE $3BE8,room_data(156)");
  L("\t\tVPOKE $3BEA,room_data(157)");
  L("\t\tVPOKE $3BEC,room_data(158)");
  L("\t\tVPOKE $3BEE,room_data(159)");
  L("\t\tVPOKE $3C10,room_data(160)");
  L("\t\tVPOKE $3C12,room_data(161)");
  L("\t\tVPOKE $3C14,room_data(162)");
  L("\t\tVPOKE $3C16,room_data(163)");
  L("\t\tVPOKE $3C18,room_data(164)");
  L("\t\tVPOKE $3C1A,room_data(165)");
  L("\t\tVPOKE $3C1C,room_data(166)");
  L("\t\tVPOKE $3C1E,room_data(167)");
  L("\t\tVPOKE $3C20,room_data(168)");
  L("\t\tVPOKE $3C22,room_data(169)");
  L("\t\tVPOKE $3C24,room_data(170)");
  L("\t\tVPOKE $3C26,room_data(171)");
  L("\t\tVPOKE $3C28,room_data(172)");
  L("\t\tVPOKE $3C2A,room_data(173)");
  L("\t\tVPOKE $3C2C,room_data(174)");
  L("\t\tVPOKE $3C2E,room_data(175)");
  L("\t\tVPOKE $3C50,room_data(176)");
  L("\t\tVPOKE $3C52,room_data(177)");
  L("\t\tVPOKE $3C54,room_data(178)");
  L("\t\tVPOKE $3C56,room_data(179)");
  L("\t\tVPOKE $3C58,room_data(180)");
  L("\t\tVPOKE $3C5A,room_data(181)");
  L("\t\tVPOKE $3C5C,room_data(182)");
  L("\t\tVPOKE $3C5E,room_data(183)");
  L("\t\tVPOKE $3C60,room_data(184)");
  L("\t\tVPOKE $3C62,room_data(185)");
  L("\t\tVPOKE $3C64,room_data(186)");
  L("\t\tVPOKE $3C66,room_data(187)");
  L("\t\tVPOKE $3C68,room_data(188)");
  L("\t\tVPOKE $3C6A,room_data(189)");
  L("\t\tVPOKE $3C6C,room_data(190)");
  L("\t\tVPOKE $3C6E,room_data(191)");
  L("\t\tVPOKE $3C90,room_data(192)");
  L("\t\tVPOKE $3C92,room_data(193)");
  L("\t\tVPOKE $3C94,room_data(194)");
  L("\t\tVPOKE $3C96,room_data(195)");
  L("\t\tVPOKE $3C98,room_data(196)");
  L("\t\tVPOKE $3C9A,room_data(197)");
  L("\t\tVPOKE $3C9C,room_data(198)");
  L("\t\tVPOKE $3C9E,room_data(199)");
  L("\t\tVPOKE $3CA0,room_data(200)");
  L("\t\tVPOKE $3CA2,room_data(201)");
  L("\t\tVPOKE $3CA4,room_data(202)");
  L("\t\tVPOKE $3CA6,room_data(203)");
  L("\t\tVPOKE $3CA8,room_data(204)");
  L("\t\tVPOKE $3CAA,room_data(205)");
  L("\t\tVPOKE $3CAC,room_data(206)");
  L("\t\tVPOKE $3CAE,room_data(207)");
  L("\t\tVPOKE $3CD0,room_data(208)");
  L("\t\tVPOKE $3CD2,room_data(209)");
  L("\t\tVPOKE $3CD4,room_data(210)");
  L("\t\tVPOKE $3CD6,room_data(211)");
  L("\t\tVPOKE $3CD8,room_data(212)");
  L("\t\tVPOKE $3CDA,room_data(213)");
  L("\t\tVPOKE $3CDC,room_data(214)");
  L("\t\tVPOKE $3CDE,room_data(215)");
  L("\t\tVPOKE $3CE0,room_data(216)");
  L("\t\tVPOKE $3CE2,room_data(217)");
  L("\t\tVPOKE $3CE4,room_data(218)");
  L("\t\tVPOKE $3CE6,room_data(219)");
  L("\t\tVPOKE $3CE8,room_data(220)");
  L("\t\tVPOKE $3CEA,room_data(221)");
  L("\t\tVPOKE $3CEC,room_data(222)");
  L("\t\tVPOKE $3CEE,room_data(223)");
  L("\t\tVPOKE $3D10,room_data(224)");
  L("\t\tVPOKE $3D12,room_data(225)");
  L("\t\tVPOKE $3D14,room_data(226)");
  L("\t\tVPOKE $3D16,room_data(227)");
  L("\t\tVPOKE $3D18,room_data(228)");
  L("\t\tVPOKE $3D1A,room_data(229)");
  L("\t\tVPOKE $3D1C,room_data(230)");
  L("\t\tVPOKE $3D1E,room_data(231)");
  L("\t\tVPOKE $3D20,room_data(232)");
  L("\t\tVPOKE $3D22,room_data(233)");
  L("\t\tVPOKE $3D24,room_data(234)");
  L("\t\tVPOKE $3D26,room_data(235)");
  L("\t\tVPOKE $3D28,room_data(236)");
  L("\t\tVPOKE $3D2A,room_data(237)");
  L("\t\tVPOKE $3D2C,room_data(238)");
  L("\t\tVPOKE $3D2E,room_data(239)");
  L("\t\tVPOKE $3D50,room_data(240)");
  L("\t\tVPOKE $3D52,room_data(241)");
  L("\t\tVPOKE $3D54,room_data(242)");
  L("\t\tVPOKE $3D56,room_data(243)");
  L("\t\tVPOKE $3D58,room_data(244)");
  L("\t\tVPOKE $3D5A,room_data(245)");
  L("\t\tVPOKE $3D5C,room_data(246)");
  L("\t\tVPOKE $3D5E,room_data(247)");
  L("\t\tVPOKE $3D60,room_data(248)");
  L("\t\tVPOKE $3D62,room_data(249)");
  L("\t\tVPOKE $3D64,room_data(250)");
  L("\t\tVPOKE $3D66,room_data(251)");
  L("\t\tVPOKE $3D68,room_data(252)");
  L("\t\tVPOKE $3D6A,room_data(253)");
  L("\t\tVPOKE $3D6C,room_data(254)");
  L("\t\tVPOKE $3D6E,room_data(255)");
  L("\tEND");
  L();
  L();
  L("tile_bitmaps:");
  if(tileIds.length===0){
    for(var y=0;y<8;y++) L("\tBITMAP \"........\"");
  } else {
    tileIds.forEach(function(id){
      var src=world.imageStore.source["TIL_"+id]||[];
      for(var y=0;y<8;y++) L("\tBITMAP \""+rowToCharBitmapStr(src[y])+"\"");
    });
  }
  L();

  L("player_bitmap:");
  var pSrc=world.imageStore.source["SPR_A"]||[];
  for(var y=0;y<8;y++) L("\tBITMAP \""+rowToSpriteBitmapStr(pSrc[y])+"\"");
  L();

  if(numNpcs>0){
    L("npc_bitmaps:");
    npcIds.forEach(function(nid){
      var src=world.imageStore.source["SPR_"+nid]||[];
      for(var y=0;y<8;y++) L("\tBITMAP \""+rowToSpriteBitmapStr(src[y])+"\"");
    });
    L();
  }

  return bas.join("\n");
}
